name: Database Migrations & Backup

on:
  push:
    branches: [ main ]
    paths: 
      - 'models/**'
      - 'scripts/migrations/**'
  schedule:
    # Run backup daily at 1 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run database migrations
      run: |
        echo "Running database migrations..."
        # Add your migration commands here
        # npm run migrate:up
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

  backup-database:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Backup MongoDB
      run: |
        echo "Creating database backup..."
        # Add backup commands here
        # mongodump --uri ${{ secrets.MONGODB_URI }} --out backup-$(date +%Y%m%d_%H%M%S)
        # Upload to S3 or other storage service

  seed-test-data:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Seed test database
      run: |
        npm run seed
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_TEST }}
