name: Performance Testing

on:
  schedule:
    # Run performance tests weekly on Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli

    - name: Create .env.local file
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/matrimony-perf" >> .env.local
        echo "NEXTAUTH_SECRET=test-secret-for-perf" >> .env.local
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 6.0

    - name: Start application
      run: |
        npm start &
        sleep 30
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000

    - name: Run Lighthouse CI
      run: lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  load-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Artillery
      run: npm install -g artillery

    - name: Create load test configuration
      run: |
        cat > load-test.yml << 'EOF'
        config:
          target: 'http://localhost:3000'
          phases:
            - duration: 60
              arrivalRate: 10
              name: "Warm up"
            - duration: 120
              arrivalRate: 20
              name: "Sustained load"
            - duration: 60
              arrivalRate: 50
              name: "Peak load"
        scenarios:
          - name: "Browse profiles"
            weight: 60
            flow:
              - get:
                  url: "/"
              - get:
                  url: "/search"
              - think: 2
          - name: "View profile details"
            weight: 30
            flow:
              - get:
                  url: "/"
              - get:
                  url: "/profile/sample-id"
              - think: 3
          - name: "Sign up flow"
            weight: 10
            flow:
              - get:
                  url: "/sign-up"
              - think: 5
        EOF

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Create .env.local file
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/matrimony-load" >> .env.local
        echo "NEXTAUTH_SECRET=test-secret-for-load" >> .env.local
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 6.0

    - name: Start application
      run: |
        npm start &
        sleep 30
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000

    - name: Run load test
      run: artillery run load-test.yml --output report.json

    - name: Generate HTML report
      run: artillery report report.json --output load-test-report.html

    - name: Upload load test results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-report
        path: |
          report.json
          load-test-report.html
        retention-days: 30
